export { Login } from './Login/Login'
export { Main } from './Main/Main'
export { Profile } from './Profile/Profile'
export { SignUp } from './SignUp/SignUp'
export { Products } from './Products/Products'
export { Category } from './Category/Category'
export { ErrorPage as Error } from './Error/ErrorPage'
